"""Core validation functionality for Plant Expression Explorer."""

from plant_expression_explorer.consistency import (
    validate_expression_de_consistency,
    validate_expression_metadata_consistency,
    validate_input_tables,
)
from plant_expression_explorer.data import CsvReadError, read_csv
from plant_expression_explorer.dataset import (
    CANDIDATE_LABEL_KEY,
    CANDIDATE_REPORT_KEY,
    CANDIDATE_SOURCE_KEY,
    CURRENT_DATASET_KEY,
    DE_RESULTS_UPLOAD_KEY,
    DEMO_SOURCE_LABEL,
    EXPRESSION_UPLOAD_KEY,
    METADATA_UPLOAD_KEY,
    CandidateResult,
    DatasetBundle,
    build_dataset_bundle,
    clear_candidate_feedback,
    clear_legacy_data_state,
    clear_uploader_state,
    get_current_dataset,
    load_demo_candidate,
    load_uploaded_candidate,
    record_candidate_failure,
    reset_data_state,
    set_current_dataset,
    table_preview,
    uploaded_source_label,
)
from plant_expression_explorer.validation import (
    IssueCode,
    Severity,
    ValidationIssue,
    ValidationReport,
    validate_de_results,
    validate_expression_matrix,
    validate_sample_metadata,
)

__all__ = [
    "CANDIDATE_LABEL_KEY",
    "CANDIDATE_REPORT_KEY",
    "CANDIDATE_SOURCE_KEY",
    "CURRENT_DATASET_KEY",
    "CsvReadError",
    "CandidateResult",
    "DEMO_SOURCE_LABEL",
    "DE_RESULTS_UPLOAD_KEY",
    "DatasetBundle",
    "EXPRESSION_UPLOAD_KEY",
    "IssueCode",
    "METADATA_UPLOAD_KEY",
    "Severity",
    "ValidationIssue",
    "ValidationReport",
    "build_dataset_bundle",
    "clear_candidate_feedback",
    "clear_legacy_data_state",
    "clear_uploader_state",
    "get_current_dataset",
    "load_demo_candidate",
    "load_uploaded_candidate",
    "read_csv",
    "record_candidate_failure",
    "reset_data_state",
    "set_current_dataset",
    "table_preview",
    "uploaded_source_label",
    "validate_de_results",
    "validate_expression_de_consistency",
    "validate_expression_matrix",
    "validate_expression_metadata_consistency",
    "validate_input_tables",
    "validate_sample_metadata",
]
